services:
  - type: web
    name: nissyonline
    runtime: node
    plan: free
    buildCommand: bash build.sh
    startCommand: node server.js
    envVars:
      - key: NISSY_PATH
        value: ./nissy
      - key: PORT
        value: 10000
